Fix export errors caused by lmdb keys being binaries
Currently in python3, lmdb gives the keys as a binary, not string which causes the export to error with:

```
File "data.py", line 47, in export_images
    image_out_path = join(image_out_dir, key + '.webp')
TypeError: can't concat str to bytes
```

You can see a Colab without and with the fix here - https://colab.research.google.com/drive/1TUULlY7FkPQXdwN7iFddjAmqwFvaz-h3